[workspace]

members = [
        "cognitive/dharma",
        "cognitive/timber",
        "cognitive/graphics",
        "cognitive/qualia",
        "cognitive/inputs",
        "cognitive/cognitive",

        "perceptia/testing",
        "perceptia/renderer_gl",
        "perceptia/frames",
        "perceptia/exhibitor",
        "perceptia/aesthetics",
        "perceptia/gears",
        "perceptia/coordination",
        "perceptia/device_manager",
        "perceptia/wayland_frontend",
        "perceptia/skylane_simple_framework",
        "perceptia/perceptia",
        "perceptia/perceptiactl",
    ]
