[workspace]

members = [
        "cognitive/dharma",
        "cognitive/timber",
        "cognitive/cognitive",
        "perceptia/qualia",
        "perceptia/testing",
        "perceptia/graphics",
        "perceptia/renderer_gl",
        "perceptia/frames",
        "perceptia/exhibitor",
        "perceptia/aesthetics",
        "perceptia/coordination",
        "perceptia/device_manager",
        "perceptia/wayland_frontend",
        "perceptia/skylane_simple_framework",
        "perceptia/perceptia",
        "perceptia/perceptiactl",
    ]

[replace]
"dharma:0.0.1" = { path = "cognitive/dharma" }
"timber:0.0.1" = { path = "cognitive/timber" }

