[workspace]

members = [
        "src/dharma",
        "src/timber",
        "src/qualia",
        "src/testing",
        "src/graphics",
        "src/renderer_gl",
        "src/output",
        "src/frames",
        "src/exhibitor",
        "src/aesthetics",
        "src/coordination",
        "src/device_manager",
        "src/wayland_frontend",
        "src/skylane_simple_framework",
        "src/perceptia",
        "src/perceptiactl",
    ]

