[package]
name = "testing"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
qualia = { path = "../qualia" }
frames = { path = "../frames" }
output = { path = "../output" }
exhibitor = { path = "../exhibitor" }

[lib]
name = "testing"
path = "lib.rs"
