[package]
name = "testing"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
cognitive-qualia = "0.0.1"
cognitive-outputs = "0.0.1"
frames = { path = "../frames" }
exhibitor = { path = "../exhibitor" }

[lib]
name = "testing"
path = "lib.rs"
