[package]
name = "frames"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
cognitive-qualia = "0.0.2"

[dev-dependencies]
testing = { path = "../testing" }

[lib]
name = "frames"
path = "lib.rs"
