[package]
name = "skylane_simple_framework"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
nix = "0.8.0"
skylane = "0.1.2"
skylane_protocols = "0.1.2"
timber = { path = "../timber" }
dharma = { path = "../dharma" }
qualia = { path = "../qualia" }

[lib]
name = "skylane_simple_framework"
path = "lib.rs"

