[package]
name = "renderer_gl"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
libc = "0.2.18"
egl = "0.2.6"
gl = "0.6.0"
timber = "0.0.1"
cognitive-graphics = "0.0.1"
cognitive-qualia = "0.0.1"

[lib]
name = "renderer_gl"
path = "lib.rs"
