[package]
name = "coordination"
version = "0.0.1"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]

[dependencies]
dharma = "0.1"
timber = "0.1"
cognitive-graphics = "0.1"
cognitive-qualia = "0.1"
gears = { path = "../gears" }

[lib]
name = "coordination"
path = "lib.rs"
